- hosts: all
  become: true
  gather_facts: True
  tasks:
    - name: Example of installing packages in ubuntu
      apt:
        pkg:
        - python-pip
        - tree
        - zip
        state: present
        update_cache: yes

    # - name: run ifconfig
    #   debug: var=hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address']

    - name: Get Disk Size
      shell:
        cmd: df -h | grep sda
      register: out
    - debug: msg="{{ out.stdout }}"

    - name: Get IP
      shell:
        cmd: ifconfig enp0s8 | grep mask
      register: out1
    - debug: msg="{{ out1.stdout.strip() }}"
